### ISSUE TITLE
GUI enhancement

### ISSUE THREAD

**Issue by KouroshKSH** [KouroshKSH/Cloud-File-SUtorage#8]
# TODO
Improve the GUI of the whole project:

- [x] server's GUI
- [x] client's GUI

**Comment by KouroshKSH** [comment]
# DID
- [x] the client's GUI now shows a simple and user-friendly pop-up screen with 3 fields to fill instead of back to back windows for initial connection

**Comment by KouroshKSH** [comment]
# DID
- [x] properly oriented buttons of client (connect, list, download, delete)
- [x] log box is now responsive to size change, has selectable text and wraps extra long text around

**Comment by KouroshKSH** [comment]
# DID
- [x] both client and server show hints and those hints change at each step for better UX
